import client from './client'

export const routesApi = {
  train: (params) => client.get('/routes/train', { params }).then((r) => r.data),
  ferry: (params) => client.get('/routes/ferry', { params }).then((r) => r.data),
  excursion: (params) => client.get('/routes/excursion', { params }).then((r) => r.data),
  checkRoute: (payload) => client.post('/routes/check', payload).then((r) => r.data),
  nearestTrainStation: (params) => client.get('/stations/nearest-train', { params }).then((r) => r.data),
  searchTrainStations: (params) => client.get('/stations/search-train', { params }).then((r) => r.data),
  searchTransportPlaces: (params) => client.get('/locations/search-transport', { params }).then((r) => r.data),
  reverseLocation: (params) => client.get('/locations/reverse', { params }).then((r) => r.data),
  nearestTransportPlace: (params) => client.get('/locations/nearest-transport', { params }).then((r) => r.data),
  savedRouteCache: (params) => client.get('/admin/route-cache', { params }).then((r) => r.data),
  geojsonImportTasks: () => client.get('/admin/geojson-import/tasks').then((r) => r.data),
  createGeojsonImportTask: (payload) => client.post('/admin/geojson-import/tasks', payload).then((r) => r.data),
  countryRoutePolicies: () => client.get('/admin/country-route-policies').then((r) => r.data),
  updateCountryRoutePolicy: (countryKey, payload) => client.put(`/admin/country-route-policies/${countryKey}`, payload).then((r) => r.data),
  adminSystemStatus: () => client.get('/admin/system-status').then((r) => r.data),
  adminDataHealth: () => client.get('/admin/data-health').then((r) => r.data),
  adminImportHistory: (params) => client.get('/admin/import-history', { params }).then((r) => r.data),
  adminRollbackImport: (historyId) => client.post(`/admin/import-history/${historyId}/rollback`).then((r) => r.data),
  adminBrokenRoutes: (params) => client.get('/admin/broken-routes', { params }).then((r) => r.data),
  adminDeleteRouteCache: (payload) => client.post('/admin/route-cache/delete', payload).then((r) => r.data),
  adminBulkUpdateCountryRoutePolicies: (payload) => client.put('/admin/country-route-policies/bulk', payload).then((r) => r.data),
  adminSearchAliases: () => client.get('/admin/search-aliases').then((r) => r.data),
  adminCreateSearchAlias: (payload) => client.post('/admin/search-aliases', payload).then((r) => r.data),
  adminDeleteSearchAlias: (aliasId) => client.delete(`/admin/search-aliases/${aliasId}`).then((r) => r.data),
  adminAuditLogs: (params) => client.get('/admin/audit-logs', { params }).then((r) => r.data),
  adminExport: (params) => client.get('/admin/export', { params }).then((r) => r.data),
  adminUsers: (params) => client.get('/admin/users', { params }).then((r) => r.data),
  adminUpdateUser: (userId, payload) => client.patch(`/admin/users/${userId}`, payload).then((r) => r.data),
  adminTrips: (params) => client.get('/admin/trips', { params }).then((r) => r.data),
  adminTripDetail: (tripId) => client.get(`/admin/trips/${tripId}`).then((r) => r.data),
  adminNormalizeTripSequence: (tripId) => client.post(`/admin/trips/${tripId}/normalize-sequence`).then((r) => r.data),
}
